#!/bin/bash
gsettings reset org.gnome.settings-daemon.plugins.media-keys volume-up
gsettings reset org.gnome.settings-daemon.plugins.media-keys volume-down
gsettings reset org.gnome.settings-daemon.plugins.media-keys volume-mute
gsettings set org.gnome.settings-daemon.plugins.media-keys screenshot-clip 'Print'
gsettings set org.gnome.settings-daemon.plugins.media-keys screenshot '<Shift>Print'
gsettings set org.gnome.settings-daemon.plugins.media-keys window-screenshot-clip '<Super>Print'
gsettings set org.gnome.settings-daemon.plugins.media-keys window-screenshot '<Shift><Super>Print'
gsettings set org.gnome.settings-daemon.plugins.media-keys area-screenshot-clip '<Control><Super>Print'
gsettings set org.gnome.settings-daemon.plugins.media-keys area-screenshot '<Control><Shift><Super>Print'
gsettings set org.gnome.settings-daemon.plugins.media-keys decrease-text-size '<Shift><Super>underscore'
gsettings set org.gnome.settings-daemon.plugins.media-keys increase-text-size  '<Shift><Super>plus'
