#!/bin/bash
# AUTHOR: frankliu197
# SPECIAL THANKS: https://unix.stackexchange.com/questions/53150/how-do-i-resize-the-active-window-to-50-with-wmctrl, rubo77
#
# USAGE:
# windowmanager [right/left] [top/bottom] OR windowmanager [top/bottom] [right/left] # By default window manager will change your window to full screen. By specifying top, bottom, right or left, you specify which half of the screen you want the current window to take.  # e.g. windowmanager right bottom
# this tells the screen to move the window to the right-bottom fourth of the screen

#define the height in px of the top system-bar:
TOPMARGIN=0
RIGHTMARGIN=0
# get width of screen and height of screen
SCREEN_WIDTH=$(xwininfo -root | awk '$1=="Width:" {print $2}')
SCREEN_HEIGHT=$(xwininfo -root | awk '$1=="Height:" {print $2}')

## for some reason different apps act differently to the same bounds thus:
X0=0
Y0=0

#make array of all the apps that act differently to resizing and check if the current app is one of them
apps=( $(xdotool search --class io.elementary) $(xdotool search --class pantheon) $(xdotool search --class Firefox) )
currentapp=$(xdotool getactivewindow)
for app in "${apps[@]}"; do
  if [[ $currentapp == $app ]]; then
    SCREEN_WIDTH=2078
    SCREEN_HEIGHT=1198
    X0=-150
    Y0=-70
    break
  fi
done

# new width and height
X=$X0
Y=$Y0


while test $# != 0
do
    case "$1" in
    right) X=$(( ($SCREEN_WIDTH - $X0) / 2 ));&
    left) WDIVIDER=2;;
    bottom) Y=$((( $SCREEN_HEIGHT - $Y0) / 2));&
    top) HDIVIDER=2;;
    esac
    shift
done

W=$(( $SCREEN_WIDTH / ${WDIVIDER-1} - $X0 / 2 - $RIGHTMARGIN ))
H=$(( $SCREEN_HEIGHT / ${HDIVIDER-1} - $Y0 / 2 - $TOPMARGIN ))
echo X=$X Y=$Y W=$W H=$H
wmctrl -r :ACTIVE: -b remove,maximized_vert,maximized_horz && wmctrl -r :ACTIVE: -e 0,$X,$Y,$W,$H
