#!/bin/bash

#downlaod node curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
sudo apt install -y nodejs

#download java
sudo apt install default-jre
sudo apt install default-jdk
sudo apt install openjdk-11-jdk



#steam 
sudo add-apt-repository -y multiverse

#pycharm
sudo add-apt-repository -y ppa:mystic-mirage/pycharm

#intllij
sudo add-apt-repositoy -y ppa:ubuntuhandbook1/apps

sudo apt update
sudo apt install -y timeshift pycharm  intellij-idea-ultimate
sudo apt install -y bumblebee bumblebee-nvidia primus linux-headers-generick 



#YGQ2J-Q26GM-R8FF8-JDC7M-KKGMV
# anki, google chrome, firefox, draw.io, discord, wechat, sebelius, microsoft word
# setup calendar, mail, firefox chrome
# keyboard shortcuts
# 
# find . -maxdepth 1 -type l -ls
#
# dconf dump /org/gnome/desktop/wm/keybindings/ > keybindings.dconf
# dconf load /org/gnome/desktop/wm/keybindings/ < keybindings.dconf
#
# fcitx include inactive with scrolling and default input method state is inactive
# sudo add-apt-repository ppa:fcitx-team/nightly
#or

#sudo add-apt-repository ppa:fcitx-team/stable
#to use different repository. You can browse two repositories via ppa webpage to check which version of Fcitx it has.

#After you add the repository, you need to use

#sudo apt-get update

#perl keybindings.pl -i keybindings2.csv
