#!/bin/bash

# install grub customizer
add-apt-repository -y ppa:danielrichter2007/grub-customizer
apt update
apt install -y grub-customizer

#install timeshift
add-apt-repository -y ppa:teejee2008/ppa
apt update
apt install -y timeshift

#install various software
apt install -y software-properties-gtk
apt install -y pavucontrol
apt install -y baobab
apt install -y xpad
apt install -y pinta
apt install -y qalculate
apt install -y audacious

#install git/hub
add-apt-repository -y ppa:cpick/hub
apt update
apt install -y git hub

#install vim
apt install -y vim vim-gtk xsel
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# add on personal changes
mkdir $HOME/Programming/
git clone https://github.com/frankliu197/Compose $HOME/Programming/
git clone https://github.com/frankliu197/bash-scripts $HOME/Programming/
ln -s ~/Programming/bash-scripts/.vimrc ~/
vim +PluginInstall +qall

echo '
. ~/Programming/bash-scripts/shortcuts
. ~/Programming/bash-scripts/gitshortcuts
. ~/Programming/bash-scripts/personalshortcuts' | sudo tee -a  ~/.bashrc

for i in windowmanager windowselector desktopshortcuts; do
  ln -s ~/Programming/bash-scripts/$i /usr/bin
done

# not garenteed to work
# $HOME/Programming/Compose/install

#install software for my repositories
apt install -y wmctrl xdotool

#keybinds
perl $HOME/Programming/bash-scripts/installscripts/keybindings/keybindings.pl -i $HOME/Programming/bash-scripts/installscripts/keybindings/keybindings.csv

# install firefox
apt install -y firefox 
apt purge -y ephiphany*

#install glances
apt install -y python3-pip
pip3 install glances

#install windscribe
apt-key adv --keyserver keyserver.ubuntu.com --recv-key FDC247B7
'deb https://repo.windscribe.com/ubuntu zesty main' | sudo tee /etc/apt/sources.list.d/windscribe-repo.list
sudo apt update
apt install windscribe-cli
windscribe login

#install deluge
apt-get install deluge
