#!/bin/bash


#install timeshift
add-apt-repository -y ppa:teejee2008/ppa
apt update
apt install -y timeshift

#install various software
apt install -y pavucontrol
apt install -y baobab
apt install -y xpad
apt install -y pinta
apt install -y qalculate
apt install -y audacious


#install glances
apt install -y python3-pip
pip3 install glances

#install windscribe
apt-key adv --keyserver keyserver.ubuntu.com --recv-key FDC247B7
'deb https://repo.windscribe.com/ubuntu zesty main' | sudo tee /etc/apt/sources.list.d/windscribe-repo.list
sudo apt update
apt install windscribe-cli
windscribe login

#install deluge
apt install deluge

# install WPS
apt install wps-office

echo you must download discord and sogou in downloads folder first
#install wine
dpkg --add-architecture i386 
wget -qO- https://dl.winehq.org/wine-builds/Release.key | sudo apt-key add -
apt-add-repository -y 'deb http://dl.winehq.org/wine-builds/ubuntu/ bionic main'
apt get update
apt-get install -y --install-recommends winehq-staging
apt install winbind

wget  https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
chmod +x winetricks
mv winetricks /usr/local/bin

#setup wine prefix
git clone https://github.com/frankliu197/wineenv ~/Games/wineenv/
mkdir ~/.wine ~/.wine32
~/Games/wineenv/32.sh winecfg
~/Games/wineenv/64.sh winecfg

#install lutris
ver=$(lsb_release -sr); if [ $ver != "18.10" -a $ver != "18.04" -a $ver != "16.04" ]; then ver=18.04; fi
echo "deb http://download.opensuse.org/repositories/home:/strycore/xUbuntu_$ver/ ./" | sudo tee /etc/apt/sources.list.d/lutris.list
wget -q https://download.opensuse.org/repositories/home:/strycore/xUbuntu_$ver/Release.key -O- | sudo apt-key add -
apt -y update
apt -y install lutris

#install steam
apt install -y steam

#install play on linux
apt install -y playonlinux

# install google-chrome
apt install -y google-chrome*

# install fcitx (and fcitx-mozc)
apt install -y fcitx
apt install -y fcitx-mozc

#install  wechatd
cd DOWNLOAD
wget -O wechat.tar.gz "https://github.com/geeeeeeeeek/electronic-wechat/releases/download/V2.0/linux-x64.tar.gz"
tar xzf wechat.tar.gz
rm wechat.tar.gz
mv *wechat* wechat
mv wechat /opt/
ln -s /opt/wechat/electronic-wechat /usr/bin

#install draw.io
wget -O draw.io.deb https://github.com/jgraph/drawio-desktop/releases/download/v9.3.1/draw.io-amd64-9.3.1.deb
apt install ./*.deb
rm *.deb

#install anki
wget -O anki.tar.bz2 https://apps.ankiweb.net/downloads/current/anki-2.1.6-linux-amd64.tar.bz2
tar jxzf anki.tar.bz2
rm anki.tar.bz2
mv *anki* anki
mv anki /opt/
cd /opt/anki/
 make install


# key: YGQ2J-Q26GM-R8FF8-JDC7M-KKGMV

#node js and java
apt install -y nodejs
apt install default-jdk
apt install -y default-jre
add-apt-repository -y ppa:linuxuprising/java
apt get update
apt-get install oracle-java11-installer

#need to add pycharm.tar
tar -xzf pycharm*.tar.gz
rm pycharm*.tar.gz
mv *pycharm* pycharm
mv pycharm /opt/
ln -s /opt/pycharm/bin/pycharm.sh /usr/bin

#need to add intellij
tar -xzf idea*.tar.gz
rm idea*.tar.gz
mv *idea* intellij
mv intellij /opt/
ln -s /opt/intellij/bin/idea.sh /usr/bin


