#!/bin/bash

# manage drivers
apt install -y software-properties-gtk

#install git/hub
add-apt-repository -y ppa:cpick/hub
apt update
apt install -y git hub xclip

#add ssh
echo Ignore the next 2 questions and press enter only
ssh-keygen -t rsa -b 4096 -C "frankliu197@gmail.com" #insert your email
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa
xclip -sel clip < ~/.ssh/id_rsa.pub

#install software for my repositories
apt install -y wmctrl xdotool

# install firefox
apt install -y firefox 
apt purge -y epiphany-browser

#install vim
apt install -y vim vim-gtk xsel
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# install grub customizer
add-apt-repository -y ppa:danielrichter2007/grub-customizer
apt update
apt install -y grub-customizer

# add on personal changes
mkdir $HOME/Programming/
git clone https://github.com/frankliu197/Compose $HOME/Programming/Compose
git clone https://github.com/frankliu197/bash-scripts $HOME/Programming/bash-scripts
ln -s ~/Programming/bash-scripts/.vimrc ~/
vim +PluginInstall +qall

echo '
. ~/Programming/bash-scripts/shortcuts
. ~/Programming/bash-scripts/gitshortcuts
. ~/Programming/bash-scripts/personalshortcuts' | sudo tee -a  ~/.bashrc

for i in windowmanager windowselector desktopshortcuts; do
  ln -s ~/Programming/bash-scripts/$i /usr/bin
done

#install custom keyboard
$HOME/Programming/Compose/install

#keybinds
perl $HOME/Programming/bash-scripts/installscripts/keybindings/keybindings.pl -i $HOME/Programming/bash-scripts/installscripts/keybindings/keybindings.csv

#remove shortcut overlay
apt remove io.elementary.shortcut-overlay

echo use "xclip -sel clip < ~/.ssh/id_rsa.pub" to copy your github ssh.  


