#!/bin/bash 
# Creates aliases for multiple git functions 
# must install hub 
# sudo add-apt-repository ppa:cpick/hub
git () {
  if [[ $1 == "commit" ]] && [[ $2 == "-A" ]]; then 
    # Adds a -A option to commit that does the command:
    # git add .
    echo Commiting: "${@:$#}"
    command git add .
    command git commit -m  "${@:$#}"
  elif [[ $1 == "push" ]] && [[ $2 == "-C" ]]; then 
    commitname="${3:-no name}"
    git commit -A "$commitname"
    echo
    echo Excecuting: git push $4 $5 
    command git push $4 $5
  elif [[ $1 == "init" ]]; then
    # init, create a repository on github, commit and push
    command git init
    hub create
    if [[ ! -f README.md ]]; then touch README.md; fi
    git push -C "First Commit" origin master  
  else 
    command git "$@"
  fi
}
